_BASE_: maskformer2_vit_base_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "MultiScaleViT"
  VIT:
    PRETRAINED_IMG_SIZE: 384
    PATCH_SIZE: 16
    OUT_INDICES: [3, 6, 9, 12]
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    OUTPUT_REVOLUTION_RATIOS: [4, 2, 1, 0.5]
    DROP_RATE: 0.2
    ATTN_DROP_RATE: 0.1
    DROP_PATH_RATE: 0.3
    FROZEN_STAGE: -1
    WEIGHTS: "pretrained_weights/B_16-i21k-300ep-lr_0.001-aug_medium1-wd_0.1-do_0.0-sd_0.0--imagenet2012-steps_20k-lr_0.01-res_384.npz"
  WEIGHTS: None
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  MAX_ITER: 737500