_BASE_: ./maskformer2_single_scale_vit_384_bs16_160k.yaml
MODEL:
  BACKBONE:
    NAME: "ConditionalViT"
  VIT:
    POOL:
      POOLING_START_LAYER: 1
      CANDIDATE_POOLING_LAYERS: [4, 7, 10]
      LAYERWISE_POOLING_RATES: [33, 34, 33]
      SIM_SCORE_THRS: [0.0065, 0.004, 0.]
      SIMILARITY_THR: 0.9
      UPDATE_STEP: 1000
      NUM_BLOCK: 1
      BLOCK_TYPE: "ssn"
      ITERS: 5
      NUM_SPIXELS: [1024, 576, 256]
      RECON_LOSS_RATIO: 1.4
      RECON_LOSS_THRS: [0., 0., 0., 0., 0., 0.]
      THR_UPDATABLE: False
      THR_UPDATE_CYCLE: 1000
      TL:
        MULTI_MODE: -1
        NUM_TOKENS: [4, 4]
        SCALES: [4, 16]
        MULTI_STAGE: 0
    UNPOOL:
      TYPE: "TSA"
      REFINED: False
      RESIDUAL: False
      K: 5
